In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score, roc_curve

In [2]:
df = pd.read_csv("Bangalore.csv")
print(df)

         Price  Area                         Location  No. of Bedrooms  \
0     30000000  3340                 JP Nagar Phase 1                4   
1      7888000  1045       Dasarahalli on Tumkur Road                2   
2      4866000  1179  Kannur on Thanisandra Main Road                2   
3      8358000  1675                     Doddanekundi                3   
4      6845000  1670                          Kengeri                3   
...        ...   ...                              ...              ...   
6202   5364000   590                       Chandapura                1   
6203   8716000  1179                    Kasavanahalli                2   
6204   7373000  1143                    Kasavanahalli                2   
6205   4985000  1680                    Kasavanahalli                3   
6206  10900000  1162                    Kasavanahalli                2   

      Resale  MaintenanceStaff  Gymnasium  SwimmingPool  LandscapedGardens  \
0          0                 1   

In [3]:
df.head(10)

,Price,Area,Location,No. of Bedrooms,Resale,MaintenanceStaff,Gymnasium,SwimmingPool,LandscapedGardens,JoggingTrack,...,LiftAvailable,BED,VaastuCompliant,Microwave,GolfCourse,TV,DiningTable,Sofa,Wardrobe,Stadium
0,30000000,3340,JP Nagar Phase 1,4,0,1,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
1,7888000,1045,Dasarahalli on Tumkur Road,2,0,0,1,1,1,1,...,1,0,1,0,0,0,0,0,0,0
2,4866000,1179,Kannur on Thanisandra Main Road,2,0,0,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
3,8358000,1675,Doddanekundi,3,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,6845000,1670,Kengeri,3,0,1,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
5,6797000,1220,Horamavu,2,0,0,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
6,20000000,2502,Thanisandra,4,0,0,1,1,1,1,...,1,0,1,0,0,0,0,0,0,0
7,7105000,1438,Ramamurthy Nagar,3,0,0,1,0,0,1,...,1,0,1,0,0,0,0,0,0,0
8,8405000,1405,Whitefield Hope Farm Junction,3,0,0,1,1,1,1,...,0,0,1,0,0,0,0,0,0,0
9,3506000,660,Electronic City Phase 1,1,0,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0


In [4]:
df.shape

(6207, 40)

In [5]:
df.columns

Index(['Price', 'Area', 'Location', 'No. of Bedrooms', 'Resale',
       'MaintenanceStaff', 'Gymnasium', 'SwimmingPool', 'LandscapedGardens',
       'JoggingTrack', 'RainWaterHarvesting', 'IndoorGames', 'ShoppingMall',
       'Intercom', 'SportsFacility', 'ATM', 'ClubHouse', 'School',
       '24X7Security', 'PowerBackup', 'CarParking', 'StaffQuarter',
       'Cafeteria', 'MultipurposeRoom', 'Hospital', 'WashingMachine',
       'Gasconnection', 'AC', 'Wifi', 'Children'splayarea', 'LiftAvailable',
       'BED', 'VaastuCompliant', 'Microwave', 'GolfCourse', 'TV',
       'DiningTable', 'Sofa', 'Wardrobe', 'Stadium'],
      dtype='object')

In [6]:
df.describe()

,Price,Area,No. of Bedrooms,Resale,MaintenanceStaff,Gymnasium,SwimmingPool,LandscapedGardens,JoggingTrack,RainWaterHarvesting,...,LiftAvailable,BED,VaastuCompliant,Microwave,GolfCourse,TV,DiningTable,Sofa,Wardrobe,Stadium
count,6.207000e+03,6207.000000,6207.000000,6207.000000,6207.000000,6207.000000,6207.000000,6207.000000,6207.000000,6207.000000,...,6207.000000,6207.000000,6207.000000,6207.000000,6207.000000,6207.000000,6207.000000,6207.000000,6207.000000,6207.000000
mean,1.058510e+07,1526.094248,2.556952,0.078782,6.208797,6.461576,6.436121,6.382471,6.396649,6.373933,...,6.438537,6.211052,6.311100,6.210569,6.181569,6.210569,6.210569,6.210569,6.171097,6.210569
std,1.410943e+07,764.845609,0.694300,0.269420,4.126883,3.752421,3.792567,3.875271,3.853661,3.888204,...,3.788782,4.123761,3.981513,4.124430,4.164294,4.124430,4.124430,4.124430,4.178546,4.124430
min,2.000000e+06,415.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5.000000e+06,1110.000000,2.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,7.368000e+06,1340.000000,3.000000,0.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,...,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000
75%,1.070000e+07,1662.500000,3.000000,0.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,...,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000
max,3.000000e+08,9900.000000,7.000000,1.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,...,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000


In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Price,6207.0,1.058510e+07,1.410943e+07,2000000.0,5000000.0,7368000.0,10700000.0,300000000.0
Area,6207.0,1.526094e+03,7.648456e+02,415.0,1110.0,1340.0,1662.5,9900.0
No. of Bedrooms,6207.0,2.556952e+00,6.943000e-01,1.0,2.0,3.0,3.0,7.0
Resale,6207.0,7.878202e-02,2.694199e-01,0.0,0.0,0.0,0.0,1.0
MaintenanceStaff,6207.0,6.208797e+00,4.126883e+00,0.0,0.0,9.0,9.0,9.0
Gymnasium,6207.0,6.461576e+00,3.752421e+00,0.0,1.0,9.0,9.0,9.0
SwimmingPool,6207.0,6.436121e+00,3.792567e+00,0.0,1.0,9.0,9.0,9.0
LandscapedGardens,6207.0,6.382471e+00,3.875271e+00,0.0,1.0,9.0,9.0,9.0
JoggingTrack,6207.0,6.396649e+00,3.853661e+00,0.0,1.0,9.0,9.0,9.0
RainWaterHarvesting,6207.0,6.373933e+00,3.888204e+00,0.0,1.0,9.0,9.0,9.0


In [8]:
df.describe(include="O").T

,count,unique,top,freq
Location,6207,302,Electronic City Phase 2,232


In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6207 entries, 0 to 6206
Data columns (total 40 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Price                6207 non-null   int64 
 1   Area                 6207 non-null   int64 
 2   Location             6207 non-null   object
 3   No. of Bedrooms      6207 non-null   int64 
 4   Resale               6207 non-null   int64 
 5   MaintenanceStaff     6207 non-null   int64 
 6   Gymnasium            6207 non-null   int64 
 7   SwimmingPool         6207 non-null   int64 
 8   LandscapedGardens    6207 non-null   int64 
 9   JoggingTrack         6207 non-null   int64 
 10  RainWaterHarvesting  6207 non-null   int64 
 11  IndoorGames          6207 non-null   int64 
 12  ShoppingMall         6207 non-null   int64 
 13  Intercom             6207 non-null   int64 
 14  SportsFacility       6207 non-null   int64 
 15  ATM                  6207 non-null   int64 
 16  ClubHo

# df.isna().sum()

In [10]:
df.duplicated().sum()

686

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [12]:
X= df[['Area']]
y= df['Price']

In [13]:
x_train , x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [15]:
y_pred = model.predict(x_test)

In [16]:
print('predicted price', y_pred)

predicted price [19920034.00398351  7882407.88115917  7485959.11663502 ...
  5460466.33788433  7284130.65469545  8386979.0360081 ]


In [17]:
import statistics
average = statistics.mean(y_pred)
print(average)

10440457.116215892


In [18]:
print("model accuracy:", (y_test, y_pred))

model accuracy: (3790    12100000
4030     6000000
2053     8180000
2683     6175000
3927     4277000
          ...   
4914     5263000
6203     8716000
3932    49800000
4520     2848000
724      5978000
Name: Price, Length: 1242, dtype: int64, array([19920034.00398351,  7882407.88115917,  7485959.11663502, ...,
        5460466.33788433,  7284130.65469545,  8386979.0360081 ]))


In [19]:
print("R² Score:", r2_score(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("intercept (base price):", model.intercept_)
print("coefficient (area):", model.coef_[0])

R² Score: 0.1283845921331216
MSE: 233939027885089.84
intercept (base price): -406975.37707315944
coefficient (area): 7208.159354984635


In [20]:
X= df[['Area']]
y= df['No. of Bedrooms']
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)
y_pred = model.predict(x_test)
print('predicted price', y_pred)

predicted price [19920034.00398351  7882407.88115917  7485959.11663502 ...
  5460466.33788433  7284130.65469545  8386979.0360081 ]


In [21]:
average= statistics.mean(y_pred)

In [22]:
print(average)

10440457.116215892


In [23]:
print("R² Score:", r2_score(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("intercept (base price):", model.intercept_)
print("coefficient (area):", model.coef_[0])

R² Score: -281003082155047.5
MSE: 138122996496101.05
intercept (base price): -406975.37707315944
coefficient (area): 7208.159354984635


In [24]:
X=df[['Area']]
y=df['Resale']
x_train, x_test, y_tarin, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
y_pred= model.predict(x_test)
print("predicted price",y_pred)

predicted price [19920034.00398351  7882407.88115917  7485959.11663502 ...
  5460466.33788433  7284130.65469545  8386979.0360081 ]


In [25]:
average= statistics.mean(y_pred)
print(average)

10440457.116215892


In [26]:
print("R² Score:", r2_score(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("intercept (base price):", model.intercept_)
print("coefficient (area):", model.coef_[0])

R² Score: -1918368971605794.0
MSE: 138123053456062.5
intercept (base price): -406975.37707315944
coefficient (area): 7208.159354984635


In [ ]:
X = df[['Area', 'No. of Bedrooms']]
y = df['Price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.6, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

svm_model = SVC(probability=True, random_state=42)
svm_model.fit(X_train_scaled, y_train)

y_pred = svm_model.predict(X_test_scaled)
y_prob = svm_model.predict_proba(X_test_scaled)

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred, digits=3))

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report

X = df[['Area', 'No. of Bedrooms']]
y = df['Price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


knn_model = KNeighborsClassifier(n_neighbors=3)
knn_model.fit(X_train_scaled, y_train)

y_pred = knn_model.predict(X_test_scaled)
y_prob = knn_model.predict_proba(X_test_scaled)

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred, digits=3))


Confusion Matrix:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification Report:
               precision    recall  f1-score   support

     2096000      0.000     0.000     0.000         1
     2100000      0.000     0.000     0.000         0
     2150000      0.000     0.000     0.000         1
     2254000      0.000     0.000     0.000         1
     2288000      0.000     0.000     0.000         7
     2300000      0.000     0.000     0.000         1
     2310000      0.000     0.000     0.000         1
     2318000      0.000     0.000     0.000         1
     2351000      0.000     0.000     0.000         1
     2355000      0.000     0.000     0.000         0
     2400000      0.125     1.000     0.222         1
     2436000      0.500     1.000     0.667         1
     2464000      1.000     1.000     1.000         2
     2487000      0.000     0.000     0.000         1
     2500000      0.000   

C:\Users\kalpe\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\kalpe\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\kalpe\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\kalpe\anaconda3\Lib\site-packages\sklea

In [ ]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from scipy.stats import uniform

baseline_svm = SVC(probability=True, random_state=42)

param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': [0.1, 1, 'scale', 'auto']
}

grid_search = GridSearchCV(baseline_svm, param_grid=param_grid, cv=5)
grid_search.fit(X_train_scaled, y_train)
print("Best parameters from GridSearchCV:", grid_search.best_params_)
print("Best score from GridSearchCV:", grid_search.best_score_)

param_dist = {
    'C': uniform(0.1, 10), 
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto'] + list(np.logspace(-3, 3, 50))
}

random_search = RandomizedSearchCV(
    baseline_svm, param_distributions=param_dist,
    n_iter=20, cv=5, random_state=42
)
random_search.fit(X_train_scaled, y_train)
print("Best parameters from RandomizedSearchCV:", random_search.best_params_)
print("Best score from RandomizedSearchCV:", random_search.best_score_)


C:\Users\kalpe\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:737: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
